#!/usr/bin/env ruby

require 'bundler/setup'
require "log_reader"

def request_argument
  STDERR.puts 'Please provide a file path, ex. #{File.basename($0)} /some/file/log'

  exit 1
end

file_path = ARGV[0] or request_argument

reader = LogReader::Reader.new(file_path)
puts reader.format
